name: fsignalr
description: "Signalr client package for flutter for integrating real-time communication using signalr protocol."
version: 1.0.0
homepage: https://github.com/acksession/fsignalr

environment:
  sdk: '>=3.3.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  logging: ^1.2.0
  tuple: ^2.0.2
  web_socket_channel: ^2.4.0
  sse_channel2: ^0.0.4
  message_pack_dart: ^2.0.1
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  collection: ^1.15.0
  flutter_lints: ^3.0.2
  quiver: ^3.2.1
  rxdart: ^0.27.7
  test: ^1.16.2

flutter:
